FROM docker.elastic.co/logstash/logstash:8.6.2@sha256:b22dd6e200c4483cb166a466ed02211fe237621a721a30875e8a9974c781cfb8
COPY ./logstash.yml /usr/share/logstash/config/
COPY ./logstash.conf /usr/share/logstash/pipeline/

